### ISSUE TITLE
Incompatible symfony/validator release - v4.2

### ISSUE THREAD

**Issue by martinknor** [Kdyby/Validator#34]
https://github.com/symfony/validator/commit/0e2b304fd0ffbd7d236ef9df4f58d4017152934f#diff-7314b7f53f439cdf2ede17404f443db0

Because there is missing typehint for `$translator` - causes error for DI Container Builder.
I think, that set default value in extension fix this.

**Comment by enumag** [comment]
Right now Kdyby/Translation is [not compatible](https://github.com/Kdyby/Translation/issues/155) with Symfony 4.2. After someone sends a PR for that we can fix Validator as well.

**Comment by enumag** [comment]
@Majkl578 That's kind of difficult. The BC break in this case is the removal of a type-hint because we rely on those for autowiring. What changes is only the reflection, but not the usage of the class. While it is a BC break for us, I don't think the Symfony team would be interested. Preserving all the type-hints would add even more restrictions to their development. Firstly they would only be able to change type-hints in new major versions and secondly there could be no LTS version where both the old deprecated way and the new way would work. If you want to report it, go ahead. I won't.
